### ISSUE TITLE
Colour pallette

### ISSUE THREAD

**Issue by zoetrope69** [University-of-Portsmouth/styleguide#8]
We should be displaying the colours we're using. This will ensure no more colours are added, we can keep the amount of colours to a minimum.

Trying to work out the best way to document using the colour pallette though.

I think some manual markup will be needed unless we create classes for colours

**Comment by johnwheal** [comment]
I think we should create classes for the colours.

**Comment by johnwheal** [comment]
I've added a WIP colours.
